### PR TITLE
Update 00-index.md

### PR DESCRIPTION
**Pull request by adaniloff**
Correction about a bad href redirection from the doc's index page.

### CODE REVIEW

**Comment by adaniloff** [comment]
@lolautruche Hello. I just changed a little number in a link and the CI failed; but it seemed that the previous PR have no issue with the the CI tool.

I wonder, have I done something wrong ?

**Comment by lolautruche** [comment]
Hi @adaniloff 
Thanks for your PR 😃 .

The failures have indeed nothing to do with your changes. They are just deprecation warnings from PHPUnit. I'm gonna fix them.

**Comment by adaniloff** [comment]
Hi! You're welcome, I was just looking for that part of the doc and I found it so I made a PR :).
I'm glad to hear that was not a problem I made from a bad branch forking / whatever :).

I'm soon gonna try this bundle so I'll let you know if I see any issues / etc or if I have any feedback.

Best regards, adaniloff

**Comment by lolautruche** [comment]
Cool ! Feel free to report any issue and/or open PRs 😄

**Pull request merged**
